// Economic calendar dictionary — types + lookup helpers.
//
// Source content lives in src/data/dictionary/{lang}.json. English is the
// canonical version (hand-authored). Other languages are generated by
// scripts/translate-dictionary.ts using Claude Haiku 4.5.

export type DictionaryLang = "en" | "ka" | "ru" | "tr" | "es"

export const DICTIONARY_LANGUAGES: Array<{ code: DictionaryLang; label: string; native: string; flag: string }> = [
  { code: "en", label: "English",  native: "English",   flag: "us" },
  { code: "ka", label: "Georgian", native: "ქართული",   flag: "ge" },
  { code: "ru", label: "Russian",  native: "Русский",   flag: "ru" },
  { code: "tr", label: "Turkish",  native: "Türkçe",    flag: "tr" },
  { code: "es", label: "Spanish",  native: "Español",   flag: "es" },
]

export type DictionaryCategory =
  | "central-bank"
  | "inflation"
  | "employment"
  | "growth"
  | "consumer"
  | "housing"
  | "manufacturing"
  | "trade"
  | "sentiment"

export const CATEGORY_META: Record<DictionaryCategory, { label: string; emoji: string; color: string }> = {
  "central-bank":  { label: "Central Bank",   emoji: "🏛️", color: "#a5b4fc" },
  inflation:       { label: "Inflation",      emoji: "📈", color: "#fb7185" },
  employment:      { label: "Employment",     emoji: "💼", color: "#10b981" },
  growth:          { label: "Growth",         emoji: "📊", color: "#fbbf24" },
  consumer:        { label: "Consumer",       emoji: "🛒", color: "#f472b6" },
  housing:         { label: "Housing",        emoji: "🏠", color: "#a78bfa" },
  manufacturing:   { label: "Manufacturing",  emoji: "🏭", color: "#fb923c" },
  trade:           { label: "Trade",          emoji: "🚢", color: "#60a5fa" },
  sentiment:       { label: "Sentiment",      emoji: "🌡️", color: "#34d399" },
}

export interface DictionaryEntry {
  id: string                          // slug, stable across translations
  name: string                        // Indicator name (translated)
  abbreviation?: string               // e.g. "NFP" — kept in original (universal)
  category: DictionaryCategory
  country: string                     // 2-letter ISO, primary country (or "GLOBAL")
  frequency: string                   // "Monthly, first Friday" (translated)
  definition: string                  // What it measures (translated)
  whyItMatters: string                // Why traders care (translated)
  marketReaction: {
    higher: string                    // "If higher than forecast: USD strengthens, stocks dip..." (translated)
    lower: string                     // "If lower than forecast: USD weakens, stocks rally..." (translated)
  }
  watchedAssets: string[]             // ["DXY", "EURUSD", "SPY"] — kept untranslated (tickers are universal)
}

export interface DictionaryFile {
  language: DictionaryLang
  generatedAt: string
  entries: DictionaryEntry[]
}

// Map calendar event names → dictionary IDs. Best-effort fuzzy match.
// Calendar event names vary across providers ("Non-Farm Payrolls" vs "Nonfarm Payrolls"
// vs "NFP"), so we normalize and do prefix matching.
export function findEntryByEventName(
  eventName: string,
  entries: DictionaryEntry[],
): DictionaryEntry | null {
  const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "")
  const target = norm(eventName)

  // Exact slug match first
  const exact = entries.find((e) => norm(e.name) === target)
  if (exact) return exact

  // Abbreviation match
  const abbr = entries.find((e) => e.abbreviation && norm(e.abbreviation) === target)
  if (abbr) return abbr

  // Substring match — pick the longest matching entry name
  const substring = entries
    .filter((e) => target.includes(norm(e.name)) || norm(e.name).includes(target))
    .sort((a, b) => b.name.length - a.name.length)
  return substring[0] ?? null
}
