import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Financial Disclaimer · Peerza.ai",
  description: "Peerza.ai is an educational social platform. Nothing on it is financial advice.",
}

export default function DisclaimerPage() {
  return (
    <>
      <h1>Financial Disclaimer</h1>
      <p className="meta">Last updated: April 30, 2026</p>

      <p>
        <strong>
          Peerza.ai is an educational social platform. Nothing on this site is financial,
          investment, legal, accounting, or tax advice. We are not a brokerage, exchange, or
          regulated financial adviser.
        </strong>
      </p>

      <h2>What we are</h2>
      <ul>
        <li>A community where people interested in markets share posts, ideas, and analysis.</li>
        <li>A simulated-trading environment for learning and practice.</li>
        <li>An educational AI tutor (Aria) that explains concepts in plain language.</li>
        <li>Games and challenges that teach how markets behave.</li>
      </ul>

      <h2>What we are not</h2>
      <ul>
        <li>A broker, exchange, custodian, or money-transmitter.</li>
        <li>A registered investment adviser.</li>
        <li>A source of personalized recommendations to buy, sell, or hold any asset.</li>
        <li>A way to make real trades or move real funds.</li>
      </ul>

      <h2>Simulated trading only</h2>
      <p>
        All trades, balances, P&amp;L, leaderboard standings, and game outcomes on Peerza.ai
        are simulated using paper money. They have no monetary value and cannot be redeemed for
        cash. Your virtual results are not a guarantee that you would achieve similar results
        with real money.
      </p>

      <h2>User-generated content</h2>
      <p>
        Posts, comments, trade ideas, polls, and analyses on Peerza.ai are the personal opinions
        of the users who write them. Users may be wrong, biased, or inexperienced. We do not
        verify the qualifications of users (except where someone is explicitly badged), and we
        do not endorse the opinions they share.
      </p>

      <h2>AI tutor (Aria)</h2>
      <p>
        Aria&apos;s responses are generated by an AI model and are intended for education only.
        They may be incorrect, outdated, or incomplete. Do not act on Aria&apos;s output without
        independent verification, and never rely on it for investment, legal, tax, or medical
        decisions.
      </p>

      <h2>Market data</h2>
      <p>
        Prices, charts, currency rates, and economic-calendar entries are sourced from
        third-party providers. They may be delayed, inaccurate, or temporarily unavailable.
        Always verify on a primary source before acting.
      </p>

      <h2>Risk warning</h2>
      <p>
        Investing in financial markets involves the risk of losing some or all of your capital.
        Leveraged products such as forex, CFDs, and options can amplify losses. Past performance
        — including simulated performance on this platform — is not indicative of future
        results. Make decisions based on your own research and, where appropriate, advice from
        a licensed professional in your jurisdiction.
      </p>

      <h2>Jurisdiction</h2>
      <p>
        Some products and information may not be available, or may be restricted, in your
        country. It is your responsibility to comply with the laws that apply to you.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about this disclaimer? Email{" "}
        <a href="mailto:legal@peerza.ai">legal@peerza.ai</a>.
      </p>
    </>
  )
}
